name = "waifubot"
type = "javascript"

compatibility_date = "2025-07-04"
compatibility_flags = ["nodejs_compat"]
[vars]
TOKEN="MTIyNzk4MTY0MjgzMzA3MjE1OA.GdTtY6.M7xqeGiHvYG1Rqn0jdqmSAKMK7H7shZX3EqnP8"
CLIENT_ID="1227981642833072158"
CLIENT_SECRET_ID="1ydpKbHACnQGiqqSscj68TCVyAuRh0L8"
PREFIX="w!"
PORT="0210"
DOMAIN="http://localhost:0210"
CALLBACK_URL="/auth/login"
FAILURE_REDIRECT="/login"
SUPPORT_SERVER="https://discord.gg/GduEUv88"
SESSION_SECRET="UW5P1qnlzKQ58980peGocuMPYLxaUdMu"
AI_API_KEY="pk-KbCixuIDmYuEXQlBkISPRmeVnXZsbArHcxbtrBHnacxGSygT"
BASE_AI_URL="https://api.pawan.krd/cosmosrp/v1"
MONGO_STRING="mongodb+srv://huyhung161111:HuyHung27082009@waifubot.zxmlvdo.mongodb.net/?retryWrites=true&w=majority&appName=WaifuBot"
SPOTIFY_ID="f64e5e9547b24cfeabd15974e3e5843f"
SPOTIFY_SECRET="66f90f1198d0496f85742acae8fc09df"
YTSR_NO_UPDATE="true"
YTDL_NO_UPDATE="true"