const cookies = [
  {
    domain: ".youtube.com",
    expirationDate: 1762177955.259658,
    hostOnly: false,
    httpOnly: true,
    name: "LOGIN_INFO",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AFmmF2swRQIhANggq_VSBK68-uApwz-7hzhQzY8aZeKUitRM1cGWzbobAiANOz6swx657f6CEAwVNdV72GEGXjeWEWoSekJQzMqw8w:QUQ3MjNmeFlnWDVRMHd5WWdXUi0xMWlZLWRDR2hRRWo4Z0xRaHlTTmNmMl93b09OQU9lWHRSbC1rQ1pvZTZLTUt4d0x0cmtWNVpBYWxMMkppa1hPb05OalVuamprQWRiT3BRMUx0MGNCaTFRdmE5T2ItN1JaZnZ3aUc4WC1KV3RQQmdaOTE2djNOa3lLTUxSY09peGtYRzFiak4zdTA4UHp3",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1755871005.601805,
    hostOnly: false,
    httpOnly: false,
    name: "PREF",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "f4=4000000&f6=40000000&tz=Asia.Saigon&f7=100",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770644946.897229,
    hostOnly: false,
    httpOnly: true,
    name: "HSID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "ARKw69-iioVZH9cYW",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770644946.897307,
    hostOnly: false,
    httpOnly: true,
    name: "SSID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "AMsjLe36FmpHgXvrH",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770644946.897329,
    hostOnly: false,
    httpOnly: false,
    name: "APISID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "4lRcbPco3BZ5Mubz/AzCoKbUIHJv0Jxu9d",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770644946.897352,
    hostOnly: false,
    httpOnly: false,
    name: "SAPISID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "hlWJVk_iZxZFDGLc/As1JrGpqR6LX5ebJr",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770644946.897372,
    hostOnly: false,
    httpOnly: false,
    name: "__Secure-1PAPISID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "hlWJVk_iZxZFDGLc/As1JrGpqR6LX5ebJr",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770644946.897392,
    hostOnly: false,
    httpOnly: false,
    name: "__Secure-3PAPISID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "hlWJVk_iZxZFDGLc/As1JrGpqR6LX5ebJr",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770644946.897534,
    hostOnly: false,
    httpOnly: false,
    name: "SID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "g.a0000AiDF-CSeW0c773SzMCFnRxdR7wG0Va8cOWaPUM8Mr1X4i1jPzlhaWAdLAVbTAsEh3cVgQACgYKASsSARASFQHGX2MiMonD6h20fpCYKTYkNaWxhxoVAUF8yKpN8oVWQ3t_sUaIMfdbEDA90076",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770644946.897555,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "g.a0000AiDF-CSeW0c773SzMCFnRxdR7wG0Va8cOWaPUM8Mr1X4i1jv8K3_PCQ-PkVaKHoFTp02gACgYKAYkSARASFQHGX2Mib96OA1daOi_2l1bMG70J-hoVAUF8yKpg3YgZwPvse0J8SM5XK4Ja0076",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770644946.897574,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "g.a0000AiDF-CSeW0c773SzMCFnRxdR7wG0Va8cOWaPUM8Mr1X4i1jxcfrvrSTEOLA_hvihnQj4wACgYKAXcSARASFQHGX2MiJAbg4aPjbJs8eT9XejhZjBoVAUF8yKq3qLS7LUINpSOArIO58jPY0076",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770818372.368781,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSIDTS",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "sidts-CjUB5H03P5cm6J5gT_D1-gb5LCJm69fuGTcyFYOFVRkl9bEk1DYBfyfidP5juQi4jxiKKqpKGBAA",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770818372.368962,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSIDTS",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "sidts-CjUB5H03P5cm6J5gT_D1-gb5LCJm69fuGTcyFYOFVRkl9bEk1DYBfyfidP5juQi4jxiKKqpKGBAA",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770818372.369077,
    hostOnly: false,
    httpOnly: false,
    name: "SIDCC",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "AKEyXzXEA6kduj4Rc8Fz-oacoDc3Jebb52xlYkI3tB0lMpegzm9iIrgjXwv4DFmiB-QZA75uJSo",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770818372.369157,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSIDCC",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AKEyXzXQogz1TO4M079XDm86gO8TuYXKyjxbk_9vp5v9iK6DMlJV8zg1OlJKlTaQEhG-_UtQvoo",
  },
  {
    domain: ".youtube.com",
    expirationDate: 1770818372.36925,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSIDCC",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AKEyXzUenAkfVBzV4QpLyLf9e0MT6IlVlbJYy_wzBaZZOYrdosHP7fpxg7hDml6fAvEhO-INeA",
  },
];

module.exports = cookies;
